# Generated by Django 5.1.4 on 2024-12-27 20:21

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
    ]
