# Generated by Django 5.1.4 on 2024-12-27 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_base_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountVerification',
            fields=[
                ('verification_code', models.CharField(max_length=6, unique=True)),
                ('expiration_time', models.DateTimeField()),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='verification', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_verification',
                'indexes': [models.Index(fields=['verification_code'], name='account_ver_verific_7565f9_idx')],
            },
        ),
    ]
