# Generated by Django 5.2.4 on 2025-07-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=255)),
                ('value', models.JSONField()),
            ],
            options={
                'db_table': 'configuration_settings',
                'constraints': [models.UniqueConstraint(fields=('key',), name='unique_config_key')],
            },
        ),
    ]
