# Generated by Django 5.2.4 on 2025-07-12 13:38

from django.db import migrations

from apps.core.types import LoggingLevel, LoggingConfigKeysType
from server import settings


def create_system_logging_level_setting(apps, schema_editor):
    """Initializes system_logging_level setting based on DEBUG"""
    ConfigurationSetting = apps.get_model('core', 'ConfigurationSetting')

    logging_level = LoggingLevel.DEBUG if settings.DEBUG else LoggingLevel.ERROR

    ConfigurationSetting.objects.create(
        key=LoggingConfigKeysType.SYSTEM_LOGGING_LEVEL,
        value=logging_level
    )


def reverse_system_logging_level_setting(apps, schema_editor):
    """Removes the system_logging_level setting"""
    ConfigurationSetting = apps.get_model('core', 'ConfigurationSetting')
    ConfigurationSetting.objects.filter(
        key=LoggingConfigKeysType.SYSTEM_LOGGING_LEVEL
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_create_configuration_settings'),
    ]

    operations = [
        migrations.RunPython(
            create_system_logging_level_setting,
            reverse_system_logging_level_setting
        )
    ]
