import type {Metadata} from "next";
import {Roboto} from "next/font/google";

import "./globals.css";
import {Toaster} from "@/components/ui/toaster";

import {Header} from "@/components/layout/Header";

import {Providers} from "@/app/providers";

const roboto = Roboto({
    subsets: ['latin', 'cyrillic'],
    weight: ['300', '400', '500', '700', '900'],
    variable: '--font-roboto',
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${roboto.variable} font-sans antialiased`}>
        <Providers>
            <Header/>
            {children}
        </Providers>
        <Toaster/>
        </body>
        </html>
    );
}
